<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '2cffec82183ee1cea088009cef9a6fc3' => $vendorDir . '/ezyang/htmlpurifier/library/HTMLPurifier.composer.php',
    '2c102faa651ef8ea5874edb585946bce' => $vendorDir . '/swiftmailer/swiftmailer/lib/swift_required.php',
    'ef49e2d680177bff6b87f195ea2420b2' => $vendorDir . '/hguenot/yii2-gftp/autoload.php',
    'ee08107f5f123445647495385b3fd6cd' => $vendorDir . '/hguenot/yii2-gsftp/autoload.php',
);
